### ISSUE TITLE
Use Custom Domains

### ISSUE THREAD

**Issue by blackHatMonkey** [GoogleCloudPlatform/jit-access#306]
We have installed JIT 1.6 on an App Engine and it's working as expected. We have setup a custom domain in our app engine as follows:
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/25112506/15911bc3-3f18-4c1e-83fd-783b15974ee2)

One issue we are running into is around multi-party approval. The link for approval is still pointing to the default App engine URL highlighted below:
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/25112506/768ac0ec-f81a-478f-966c-1e5f8a328073)

The `app.yaml` config is:
```yaml
runtime: java17
instance_class: F2
service_account: REDACTED
service: jitaccess
env_variables:
    RESOURCE_SCOPE: organizations/REDACTED
    RESOURCE_CATALOG: PolicyAnalyzer
    ACTIVATION_TIMEOUT: 240 
    RESOURCE_CUSTOMER_ID: REDACTED
    JUSTIFICATION_HINT: "ticket number or reason"
    JUSTIFICATION_PATTERN: ".*"
    SMTP_HOST: smtp.office365.com
    SMTP_SENDER_ADDRESS: REDACTED
    SMTP_USERNAME: REDACTED
    SMTP_SECRET: projects/REDACTED/secrets/jitaccess-smtp/versions/1
    AVAILABLE_PROJECTS_QUERY: "labels:REDACTED"
```

`dispatch.yaml` config:
```yaml
dispatch:
# route custom domain to the jitaccess service
- url: "REDACTED/*"
  service: jitaccess
```

Is it possible to set a configuration so the link to the email points to the custom domain instead?
