### ISSUE TITLE
Recursive folder listing does not work using AssetInventory API

### ISSUE THREAD

**Issue by rwblokzijl** [GoogleCloudPlatform/jit-access#413]
While the listing of the roles within a project works fine and it also grants access just fine, it seems like listing the projects that are nested deeper than the root "scope" folder does not work.

This is advertised in the [docs](https://googlecloudplatform.github.io/jit-access/configuration-options/):
![image](https://github.com/GoogleCloudPlatform/jit-access/assets/446634/22c09f2e-c332-4036-ba10-b2e2e72f2467)

Our setup is as follows

```yaml
- folders/jitaccess: # Scope of the JIT app
  - folders/nested_1:
    - projects/project_1 # Includes a JIT role
    - projects/project_2 # Includes a JIT role
  - folders/nested_2:
    - projects/project_3 # Includes a JIT role
```

When manually inputting the folder IT of project_1 into the project selector everything works fine, its only the nested listing that is broken...
When the projects were directly inside the `folders/jitaccess` the listing worked fine.
